apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozoo-deployment
  namespace: ozoo
  labels:
    app: ozoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ozoo
  template:
    metadata:
      labels:
        app: ozoo
    spec:
      containers:
      - name: ozoo
        image: alemarchdev/ozoo-app:v1.06
        envFrom:
        - configMapRef:
            name: ozoo-app-config
        - secretRef:
            name: ozoo-app-secrets
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: ozoo-data
          mountPath: /data
      volumes:
      - name: ozoo-data
        persistentVolumeClaim:
          claimName: ozoo-pvc
      imagePullSecrets:
      - name: regcred
