apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ozoo
resources:
  - namespace.yaml
  - secret.enc.yaml
  - mongodb-pvc.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
