apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/proxmox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
resources:
  - apps/kitchenowl
  - ../infrastructure/kitchenowl-chart-source.yaml

