apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: proxmox
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/proxmox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
resources:
  - flux-system
  - infra
  - apps
