apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kitchenowl
resources:
  - namespace.yaml
  - kitchenowl-secret.enc.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: kitchenowl-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true

